// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy5k3nCV_8bwDsjWcN_4Ir4MVDKpwylfk',
    appId: '1:40267974736:web:7a52d17e9ca16a6195e955',
    messagingSenderId: '40267974736',
    projectId: 'dot-test-6f514',
    authDomain: 'dot-test-6f514.firebaseapp.com',
    storageBucket: 'dot-test-6f514.appspot.com',
    measurementId: 'G-LSYCRQMHRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUsHglh3AKtNmmE86q6awE1mWR5n2h9s',
    appId: '1:40267974736:android:06ccd99aa66c4da695e955',
    messagingSenderId: '40267974736',
    projectId: 'dot-test-6f514',
    storageBucket: 'dot-test-6f514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_SDI02N4e1cok3w_-PC_utKpwt0TuFlM',
    appId: '1:40267974736:ios:389545b7f12dfe7d95e955',
    messagingSenderId: '40267974736',
    projectId: 'dot-test-6f514',
    storageBucket: 'dot-test-6f514.appspot.com',
    iosClientId: '40267974736-le23th75im5cr2ijd9uncpudobvf665r.apps.googleusercontent.com',
    iosBundleId: 'com.example.dot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_SDI02N4e1cok3w_-PC_utKpwt0TuFlM',
    appId: '1:40267974736:ios:389545b7f12dfe7d95e955',
    messagingSenderId: '40267974736',
    projectId: 'dot-test-6f514',
    storageBucket: 'dot-test-6f514.appspot.com',
    iosClientId: '40267974736-le23th75im5cr2ijd9uncpudobvf665r.apps.googleusercontent.com',
    iosBundleId: 'com.example.dot',
  );
}
